FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build || (echo "BUILD FAILED" && cat /app/node_modules/.bin/nest && exit 1)

EXPOSE 3000

CMD ["node", "dist/main"]
